import pandas as pd

# Sample customer data
data = [
    [
        "ABC Corp Ltd",
        "GENERAL",
        "GENERAL",
        "A Class",
        "GENERAL",
        "27-01-2025",
        "AAACA3622D",
        "Office",
        "123 Main St",
        "MUMBAI",
        "400001",
        "1234567890",
        "5564567890",
        "PAN No.",
        "AOACA3622D",
        "Paid",
        "To Pay",
        "To Be Billed",
        "Booking",
        "Booking Branch",
        "AHMEDABAD",
        "MUMBAI",
        20,
        20000,
        "MAHARASHTRA",
        "TRANSPORTATION",
        "27AALMN1234PSZO",
    ],
    [
        "XYZ Pvt Ltd",
        "GENERAL",
        "GENERAL",
        "B Class",
        "GENERAL",
        "01-02-2025",
        "BBACA1234C",
        "Office",
        "456 Market St",
        "PUNE",
        "411001",
        "9876543210",
        "9988776655",
        "PAN No.",
        "BBACA1234C",
        "Paid",
        "To Pay",
        "To Be Billed",
        "Booking",
        "Booking Branch",
        "DELHI",
        "BANGALORE",
        30,
        25000,
        "KARNATAKA",
        "TRANSPORTATION",
        "29AAXYZ5678D1ZQ",
    ],
]

# Column names
columns = [
    "PartyName",
    "PartyCategory",
    "PartyIndustryType",
    "PartyGrade",
    "PartyGroup",
    "EffectiveFromDate",
    "PANNo",
    "AddressType",
    "AddressLine",
    "City",
    "PinCode",
    "ContactNo",
    "Mob",
    "RegistrationHead",
    "RegistrationNumber",
    "PaymentType1",
    "PaymentType2",
    "PaymentType3",
    "BillingOn",
    "BillingLocationType",
    "CollectionLocation",
    "SubmissionLocation",
    "CreditDays",
    "CreditLimit",
    "State",
    "BusinessVertical",
    "GSTNumber",
]

# Create a DataFrame and save to an Excel file
df = pd.DataFrame(data, columns=columns)
df.to_excel("customer_data.xlsx", index=False)
print("Excel file 'customer_data.xlsx' created successfully.")
