# Generated by Django 5.2.1 on 2025-05-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrganizationalTestStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_id", models.IntegerField()),
                ("organizational_hierarchy", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
                ("rerun_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_id", models.IntegerField()),
                ("description", models.TextField()),
                ("test_data", models.TextField(blank=True, null=True)),
                ("actual_data", models.TextField(blank=True, null=True)),
                ("expected_data", models.TextField(blank=True, null=True)),
                ("status", models.CharField(max_length=20)),
                ("remark", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TestSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=20)),
                ("module_name", models.CharField(max_length=100)),
                ("passed_tests", models.IntegerField()),
                ("failed_tests", models.IntegerField()),
                ("total_test_cases", models.IntegerField()),
            ],
        ),
    ]
