# Generated by Django 5.2.1 on 2025-05-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrganizationalTestStatus",
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[("Passed", "Passed"), ("Failed", "Failed")], max_length=10
            ),
        ),
    ]
